//
//  i18n.swift
//  bbforum
//
//  Generated by executing $python i18n.py
//  Copyright © 2016 YUHO. All rights reserved.
//

import Foundation

class i18n {

	class var cancel: String {
		get {
			return NSLocalizedString("cancel", comment: "")
		}
	}

	class var close: String {
		get {
			return NSLocalizedString("close", comment: "")
		}
	}

	class var yes: String {
		get {
			return NSLocalizedString("yes", comment: "")
		}
	}

}